class Settings(object):
    def __init__(self):
        self.randomDemonLevels = False              # Randomize demon levels (enables encounter randomizer)
        self.randomSkills = False                   # Randomize demon starting and learned skills
        self.scaledSkills = False                   # Ensure demons have appropriately strong skills for their level
        self.randomInnates = False                  # Randomize demon innate skills
        self.potentialWeightedSkills = False        # Weight demon skills based on their skill potentials and stats
        self.randomPotentials = False               # Randomize demon skill potentials
        self.scaledPotentials = False               # Scale demon potentials based on level
        self.multipleUniques = False                # Allows unique skills to be assigned to more than one demon
        self.randomMusic = False                    # Boss music is randomized
        self.checkBasedMusic = False                # Boss music is based on check rather than boss demon
        self.randomShopItems = False                # Randomizes what items are sold in the shop
        self.randomShopEssences = False             # Randomizes what essences are sold in the shop
        self.randomEnemyDrops = False               # Randomizes items that enemies drop
        self.randomMiracleUnlocks = False           # Shuffles what miracles are unlocked at each abscess
        self.randomMiracleCosts = False             # Randomizes the glory cost of miracles
        self.reverseDivineGarrisons = False         # Reverses the order in which you learn divine garrison miracles so you get +3 stock upgrades early
        self.forcedEarlyMiracles = []               # The list of miracles that are forced to be available in the first abscess or at the start
        self.vanillaRankViolation = False           # Forces rank violation to be vanilla to avoid breaking the game too easily
        self.randomChests = False                   # Randomizes the items/macca/essences gained from overworld chests
        self.selfRandomizeNormalBosses = False      # Randomize story and sidequest bosses only with each other
        self.mixedRandomizeNormalBosses = False     # Randomize story and sidequest bosses with all bosses
        self.randomizeLucifer = False               # Include the final boss in randomization (goes into the normal boss pool)
        self.selfRandomizeAbscessBosses = False     # Randomize abscess bosses only with each other
        self.mixedRandomizeAbscessBosses = False    # Randomize abscess bosses with all bosses
        self.selfRandomizeOverworldBosses = False   # Randomize punishing foes only with each other
        self.mixedRandomizeOverworldBosses = False  # Randomize punishing foes with all bosses
        self.selfRandomizeSuperbosses = False       # Randomize superbosses only with each other
        self.mixedRandomizeSuperbosses = False      # Randomize superbosses foes with all bosses
        self.selfRandomizeMinibosses = False        # Randomize minibosses and weaker quest bosses only with each other
        self.mixedRandomizeMinibosses = False       # Randomize minibosses and weaker quest bosses with all bosses
        self.randomInheritance = False              # Randomize to which demons unique skills belong to
        self.freeInheritance = False                # Make unique skills freely inheritable
        self.restrictLunationFlux = False           # Prevent lunation flux from occuring on multiple demons or being inherited
        self.randomRaces = False                    # Randomize normal demons' races
        self.randomAlignment = False                # Randomize the alignment of demons
        self.ensureDemonJoinLevel = False           # Ensures the demons that join after quests have the same level as the original demon from that quest
        self.scaleItemsToArea = False               # Scales items (drops/rewards/shops) to be similiar to original progression wise
        self.randomizeMimanRewards = False          # Randomizes the rewards for gathering Miman
        self.randomizeMissionRewards = False        # Randomizes the rewards of mission
        self.randomDemonStats = False               # Randomizes the stat modifiers for playable demons
        self.fixUniqueSkillAnimations = False       # Replaces unique skill animations with those of normal skills to avoid the game hanging
        self.scaleBossDamage = False                # Bosses' damage dealt multiplier will be based on the level difference of the check they replace
        self.scaleBossPressTurnsToCheck = False     # Boss press turns will match the check instead of the boss
        self.ishtarPressTurns = 3                   # The number of press turns Ishtar/The Ishtar check should use
        self.randomizeIshtarPressTurns = False      # If true, overrides the ishtarPressTurns value and randomly assigns 1-8 press turns for Ishtar
        self.reduceCompendiumCosts = False          # Reduces the cost of active skills in the compendium
        self.preventEarlyAmbush = False             # Prevents story event encounters to be ambushes before Hydras check
        self.bossDependentAmbush = False            # Ambushes are boss dependent and moved with bosses if possible
        self.nerfBossHealing = False                # Reduces the power of enemy-only healing skills (except diarahan/mediarahan)
        self.scaleBossInstakillRates = False        # Boss instakill susceptibility will be based on check instead of the boss itself
        self.randomizeGiftItems = False             # Randomizes a plethora of items given through events (mostly talismans and periapts through NPCs or story)
        self.combineKeyItemPools = False            # Combines the key item pools of Miman, Mission, and Gifts
        self.buffGuestYuzuru = False                # Gives guest yuzuru level 99 and 99 to all stats to help with the first Labolas check
        self.expMultiplier = 1                      # Determines how much exp demons and quests provide